package com.example.marvellobby.rift.presentation

data class HeroInfo(val archetype:String,val summary:String,val attack:String,val gadget:String,val ultimate:String,val hyper:String,val control:Int,val difficulty:Int)
fun heroInfo(key:String,pt:Boolean):HeroInfo=when(key) {
    "iron-man"->if(pt)HeroInfo("PRECISÃO · MOBILIDADE","Controle a distância e escolha a linha de tiro.","Repulsores rápidos, três cargas regenerativas.","Propulsão e cinco segundos de tiros perfurantes mais fortes.","Impacto de energia na área indicada.","15 s de mobilidade ampliada e tiros perfurantes.",1,3)
        else HeroInfo("PRECISION · MOBILITY","Keep your distance and choose your firing lane.","Fast repulsors with three regenerating charges.","Thruster dash and five seconds of stronger piercing shots.","Energy impact at the aimed location.","15 s of improved mobility and piercing shots.",1,3)
    "hulk"->if(pt)HeroInfo("TANQUE · IMPACTO","Encurte a distância. Resista e domine grupos.","Golpes pesados sem gastar cargas.","Avanço curto com impacto físico.","Salto até a área indicada e impacto no chão.","15 s de resistência e ondas de impacto após cada golpe.",3,1)
        else HeroInfo("TANK · IMPACT","Close the gap. Withstand damage and dominate groups.","Heavy strikes without ammo cost.","Short forward charge with physical impact.","Leap to the aimed area and smash the ground.","15 s of resistance and shockwaves after each strike.",3,1)
    "thor"->if(pt)HeroInfo("BRUISER · CONTROLE","Alterne entre alcance e pressão próxima.","Mjolnir em melee ou arremesso com cargas.","Alterna golpe e arremesso do martelo.","Raio em área no ponto indicado.","15 s de impactos elétricos e arremessos perfurantes.",4,3)
        else HeroInfo("BRUISER · CONTROL","Alternate between range and close pressure.","Mjolnir melee or charged hammer throws.","Switch between melee and hammer throws.","Area lightning at the aimed location.","15 s of electric impacts and piercing throws.",4,3)
    "wolverine"->if(pt)HeroInfo("ASSASSINO · REGENERAÇÃO","Entre, pressione e use a regeneração para continuar.","Garras e combos gratuitos. Regenera fora do dano.","Avanço agressivo na direção da mira.","Investida de garras até a região indicada.","15 s de regeneração, movimento e dano ampliados.",1,4)
        else HeroInfo("ASSASSIN · REGENERATION","Close in, apply pressure and recover between hits.","Free claw combos. Regenerates between incoming hits.","Aggressive lunge in the aiming direction.","Claw rush toward the aimed location.","15 s of improved regeneration, movement and damage.",1,4)
    "doctor-strange"->if(pt)HeroInfo("MAGO · CONTROLE","Posicionamento e zonas mágicas decidem o combate.","Projéteis mágicos com slow e cargas regenerativas.","Portal na direção da mira; controla a área de chegada.","Zona mágica com impactos durante três segundos.","15 s de magias triplas perfurantes sem dano triplo por alvo.",5,5)
        else HeroInfo("MAGE · CONTROL","Positioning and magical zones decide the fight.","Magic projectiles with slow and regenerating charges.","Portal in your aiming direction; controls the arrival area.","A magical zone pulses over three seconds.","15 s of triple piercing spells without triple damage per target.",5,5)
    else->if(pt)HeroInfo("HÍBRIDO · CONTROLE","Teia, aproximação, golpe. Alterne para dominar.","Teias com 50% slow; melee gratuito. Segure 2 s no melee para consumir uma carga e avançar.","Alterna entre TEIA e MELEE livremente.","Explosão de teias na região indicada.","15 s: três teias por disparo ou melee ampliado. Troque de modo livremente.",4,4)
        else HeroInfo("HYBRID · CONTROL","Web, close the gap, strike. Switch styles to master it.","Webs slow by 50%; free melee. Hold melee for 2 s to spend one charge and lunge.","Freely switch between WEB and MELEE.","Web explosion at the aimed location.","15 s: three webs per shot or enhanced melee. Switch freely.",4,4)
}
